const V='0.2';
const round2p5=n=>Math.round(n/2.5)*2.5;
const e1rm=(w,r)=>Math.round(w*(1+r/30));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
let view='home';
const defaultState={version:V,currentDay:0,maxes:{deadlift:157,squat:129,bench:108,viking:93},logs:[],accessories:{},notes:'',recovery:{sleep:3,energy:3,stress:3,shoulder:'OK',hip:'OK'}};
let state=JSON.parse(localStorage.getItem('forgePRS')||'null')||structuredClone(defaultState);
state.version=V; state.logs ||= []; state.accessories ||= {}; state.recovery ||= defaultState.recovery;
const save=()=>localStorage.setItem('forgePRS',JSON.stringify(state));
const phases=[
 {name:'Phase 1',note:'Average intensity / average volume',acc:'3–4 sets of 8–12',sets:{speed:[6,2,.625],reps:[3,6,.80],power:[3,3,.85]}},
 {name:'Phase 2',note:'High intensity / lower volume',acc:'3–4 sets of 6–10',sets:{speed:[5,2,.70],reps:[5,4,.825],power:[3,2,.90]}},
 {name:'Phase 3',note:'Lower intensity / higher volume',acc:'4 sets of 8–15',sets:{speed:[7,3,.625],reps:[3,6,.775],power:[4,3,.80]}},
 {name:'Peak',note:'Cut fluff. Practise heavy work.',acc:'1–2 easy sets only',sets:{speed:[3,2,.70],reps:[3,3,.80],power:[4,3,.90]}}
];
const blocks=[
 [{lift:'deadlift',type:'speed',title:'Deadlift Speed',acc:['Romanian Deadlift','Landmine Row','Pull-ups','Ab Wheel']},{lift:'bench',type:'reps',title:'Bench Reps',acc:['Incline DB Press','Weighted Dips','Rolling DB Extensions','Lateral Raises']},{lift:'squat',type:'power',title:'Squat Power',acc:['Pause Squat','Bulgarian Split Squat','Romanian Deadlift','Ab Wheel']},{lift:'viking',type:'speed',title:'Viking Press Speed',acc:['Touch & Go Bench','Chest Supported DB Row','Band Pull Aparts','Hammer Curls']}],
 [{lift:'deadlift',type:'reps',title:'Deadlift Reps',acc:['Block Pull or RDL','Landmine Row','Pull-ups','Farmers Carry']},{lift:'bench',type:'power',title:'Bench Power',acc:['Flat DB Press','Weighted Dips','Skull Crushers','Lateral Raises']},{lift:'squat',type:'speed',title:'Squat Speed',acc:['Front Squat','Bulgarian Split Squat','Good Morning','Hanging Knee Raises']},{lift:'viking',type:'reps',title:'Viking Press Reps',acc:['Touch & Go Bench','Chest Supported DB Row','Rear Delt Raise','DB Curl']}],
 [{lift:'deadlift',type:'power',title:'Deadlift Power',acc:['Deficit Deadlift or RDL','Landmine Row','Pull-ups','Suitcase Carry']},{lift:'bench',type:'speed',title:'Bench Speed',acc:['Close Grip Bench','Incline DB Press','Dips','Band Pull Aparts']},{lift:'squat',type:'reps',title:'Squat Reps',acc:['Pause Squat','Walking Lunges','Romanian Deadlift','Ab Wheel']},{lift:'viking',type:'power',title:'Viking Press Power',acc:['Touch & Go Bench','Chest Supported DB Row','Lateral Raises','Hammer Curls']}]
];
function go(v){view=v;render()}
function session(i=state.currentDay){let phase=Math.min(3,Math.floor(i/12)),block=Math.floor((i%12)/4),day=i%4;return {...blocks[block][day],phase,block,day,week:Math.floor(i/4)+1,sessionNo:i+1}}
function work(s){let p=phases[s.phase].sets[s.type],max=state.maxes[s.lift],tm=s.phase<3?max*.95:max;return{sets:p[0],reps:p[1],pct:p[2],tm:round2p5(tm),weight:round2p5(tm*p[2])}}
function warmups(w){return [20,w*.4,w*.55,w*.7,w*.85].map(round2p5).filter((x,i,a)=>x<w&&a.indexOf(x)===i).map((x,i)=>({w:x,r:i<2?5:i==2?3:i==3?2:1}))}
function coach(){let r=state.recovery,score=(+r.sleep)+(+r.energy)+(6-(+r.stress)); if(score<=7)return '<span class="warn">Recovery low: skip AMRAP and leave reps in reserve.</span>'; if(score>=12)return '<span class="ok">Recovery good: AMRAP allowed if bar speed is there.</span>'; return 'Normal day: hit the work, no missed reps.'}
function render(){document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));let t=document.getElementById('tab'+view[0].toUpperCase()+view.slice(1)); if(t)t.classList.add('active'); app.innerHTML=`<div class="wrap">${({home,log,history,progress,settings})[view]()}</div>`}
function home(){let s=session(),w=work(s),total=state.maxes.deadlift+state.maxes.squat+state.maxes.bench;return `<div class="top"><div class="brand">Forge</div><div class="pill">v${V}</div></div><div class="card hero"><div class="muted">${phases[s.phase].name} · Week ${s.week} · Session ${s.sessionNo}/48</div><div class="title">${s.title}</div><p class="muted">${phases[s.phase].note}</p><div class="grid"><div class="stat"><span class="muted">Today</span><b>${w.sets}×${w.reps}</b><span>@ ${w.weight}kg</span></div><div class="stat"><span class="muted">Training max</span><b>${w.tm}</b><span>kg</span></div><div class="stat"><span class="muted">Total</span><b>${total}</b><span>kg / 500</span></div><div class="stat"><span class="muted">Coach</span><b style="font-size:18px">${coach()}</b></div></div><button style="width:100%;margin-top:16px" onclick="go('log')">Start workout</button></div><div class="card"><b>Accessories</b><p class="muted small">${phases[s.phase].acc}</p>${s.acc.map(a=>`<div class="row"><span>${a}</span><span class="tag">${lastAcc(a)}</span></div>`).join('')}</div><div class="card"><b>Cycle progress</b><p class="muted small">Don't restart if life gets in the way. Just do the next session.</p><div class="phasegrid">${Array.from({length:48},(_,i)=>`<div class="box ${i<state.currentDay?'on':''}"></div>`).join('')}</div></div>`}
function lastAcc(a){let x=state.accessories[a];return x&&x.w?`${x.w}kg last`:'new'}
function log(){let s=session(),w=work(s);return `<div class="top"><div><div class="brand">Workout</div><div class="muted small">${s.title}</div></div><button class="secondary" onclick="finish()">Finish</button></div><div class="card"><p class="muted">${w.sets} sets × ${w.reps} reps @ ${w.weight}kg. Last set can be AMRAP. No missed reps.</p><b>Warm-up</b>${warmups(w.weight).map(x=>`<div class="row"><span>${x.w}kg × ${x.r}</span><button class="check" onclick="tick(this)">○</button></div>`).join('')}<b>Working sets</b><div id="mainsets">${Array.from({length:w.sets},(_,i)=>`<div class="set"><span>Set ${i+1}${i==w.sets-1?' +':''}</span><input value="${w.weight}" inputmode="decimal"><input value="${w.reps}" inputmode="numeric"><button class="check" onclick="tick(this)">○</button></div>`).join('')}</div><button class="ghost" style="width:100%;margin-top:10px" onclick="calcMain()">Calculate estimated max</button><div id="mainResult" class="muted" style="margin-top:12px"></div></div><div class="card"><b>Accessories</b>${s.acc.map(accHtml).join('')}</div><div class="card"><b>Session notes</b><textarea id="sessionNotes" placeholder="What felt good? Any pain? Anything to change next time?"></textarea></div>`}
function tick(el){el.classList.toggle('done');el.textContent=el.classList.contains('done')?'✓':'○'}
function clean(s){return s.replace(/[^a-z0-9]/gi,'')}
function accHtml(name){let x=state.accessories[name]||{w:'',r1:'',r2:'',r3:''};return `<div class="card" style="background:#101014"><b>${name}</b><div class="muted small">Last: ${x.w?`${x.w}kg · ${x.r1}/${x.r2}/${x.r3} reps`:'nothing logged yet'}</div><div class="set"><span>Weight</span><input id="${clean(name)}w" value="${x.w}" inputmode="decimal"><input disabled value="kg"><span></span></div>${[1,2,3].map(i=>`<div class="set"><span>Set ${i}</span><input id="${clean(name)}r${i}" value="${x['r'+i]}" inputmode="numeric"><input disabled value="reps"><span></span></div>`).join('')}<button class="secondary" onclick="saveAcc('${name.replaceAll("'","\\'")}')">Save accessory</button></div>`}
function saveAcc(name){state.accessories[name]={w:val(clean(name)+'w'),r1:val(clean(name)+'r1'),r2:val(clean(name)+'r2'),r3:val(clean(name)+'r3')};save();render()}
function val(id){return document.getElementById(id)?.value||''}
let pendingMain=null;
function calcMain(){let s=session(),rows=[...document.querySelectorAll('#mainsets .set')],last=rows.at(-1).querySelectorAll('input'),wt=parseFloat(last[0].value||0),reps=parseInt(last[1].value||0),est=e1rm(wt,reps);pendingMain={lift:s.lift,est,wt,reps}; mainResult.innerHTML=`Estimated 1RM: <b>${est}kg</b> ${est>state.maxes[s.lift]?'<span class="ok">new estimated PR saved on finish</span>':''}`}
function finish(){let s=session(),w=work(s); if(!pendingMain) calcMain(); let log={id:uid(),date:new Date().toISOString(),session:state.currentDay,title:s.title,lift:s.lift,type:s.type,phase:s.phase,weight:w.weight,sets:w.sets,reps:w.reps,est:pendingMain?.est||state.maxes[s.lift],notes:val('sessionNotes')}; state.logs.unshift(log); if(log.est>state.maxes[s.lift]) state.maxes[s.lift]=log.est; state.currentDay=Math.min(47,state.currentDay+1); save(); pendingMain=null; go('home')}
function history(){return `<div class="top"><div class="brand">History</div><button class="secondary" onclick="exportData()">Export</button></div>${state.logs.length?state.logs.map(l=>`<div class="card"><div class="row"><b>${l.title}</b><span class="tag">${new Date(l.date).toLocaleDateString()}</span></div><div class="grid"><div class="stat"><span class="muted">Work</span><b>${l.weight}</b><span>kg</span></div><div class="stat"><span class="muted">Sets</span><b>${l.sets}×${l.reps}</b></div><div class="stat"><span class="muted">e1RM</span><b>${l.est}</b><span>kg</span></div><div class="stat"><span class="muted">Phase</span><b>${l.phase+1}</b></div></div>${l.notes?`<p class="muted">${l.notes}</p>`:''}</div>`).join(''):'<div class="card"><b>No workouts logged yet.</b><p class="muted">Start your first session from Today.</p></div>'}`}
function progress(){let total=state.maxes.deadlift+state.maxes.squat+state.maxes.bench,p=Math.min(100,total/500*100);return `<div class="top"><div class="brand">Progress</div><div class="pill">${Math.round(p)}%</div></div><div class="card hero"><div class="big">${total}kg</div><div class="muted">Powerlifting total · target 500kg</div><div class="bar" style="margin-top:14px"><span style="width:${p}%"></span></div></div><div class="grid">${Object.entries(state.maxes).map(([k,v])=>`<div class="stat"><span class="muted">${cap(k)}</span><b>${v}</b><span>kg</span></div>`).join('')}</div><div class="card"><b>Recovery</b><div class="split"><label>Sleep<select id="sleep">${opts(state.recovery.sleep)}</select></label><label>Energy<select id="energy">${opts(state.recovery.energy)}</select></label></div><label>Stress<select id="stress">${opts(state.recovery.stress)}</select></label><div class="split"><label>Shoulder<input id="shoulder" value="${state.recovery.shoulder}"></label><label>Hip<input id="hip" value="${state.recovery.hip}"></label></div><button style="width:100%;margin-top:12px" onclick="saveRecovery()">Save recovery</button></div>`}
function opts(v){return [1,2,3,4,5].map(n=>`<option ${+v===n?'selected':''}>${n}</option>`).join('')}
function saveRecovery(){state.recovery={sleep:val('sleep'),energy:val('energy'),stress:val('stress'),shoulder:val('shoulder'),hip:val('hip')};save();render()}
function settings(){return `<div class="top"><div class="brand">Setup</div><button class="secondary" onclick="resetApp()">Reset</button></div><div class="card"><b>Current estimated 1RMs</b>${Object.keys(state.maxes).map(k=>`<label>${cap(k)} kg</label><input id="m_${k}" value="${state.maxes[k]}" inputmode="decimal">`).join('')}<button style="width:100%;margin-top:16px" onclick="saveMaxes()">Save maxes</button></div><div class="card"><b>Programme position</b><label>Current session number 1–48</label><input id="day" value="${state.currentDay+1}" inputmode="numeric"><button class="secondary" style="width:100%;margin-top:12px" onclick="saveDay()">Save position</button></div><div class="card"><b>Equipment profile</b><p class="muted">Rack, barbell, Ironmaster dumbbells, landmine, Viking Press, dip handles, pull-up bar, bands. No cable stack or leg machines.</p></div>`}
function cap(k){return k[0].toUpperCase()+k.slice(1)}
function saveMaxes(){Object.keys(state.maxes).forEach(k=>state.maxes[k]=parseFloat(val('m_'+k)||0));save();go('home')}
function saveDay(){state.currentDay=Math.max(0,Math.min(47,parseInt(val('day')||1)-1));save();go('home')}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='forge-prs-data.json';a.click()}
function resetApp(){if(confirm('Clear all Forge data on this device?')){state=structuredClone(defaultState);save();go('home')}}
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
save();render();
