const round2p5=n=>Math.round(n/2.5)*2.5;
const e1rm=(w,r)=>Math.round(w*(1+r/30));
let view='home';
const defaultState={currentDay:0, maxes:{deadlift:157,squat:129,bench:108,viking:93}, logs:[], accessories:{}, recovery:{sleep:3,energy:3,stress:3,shoulder:'OK',hip:'OK'}};
let state=JSON.parse(localStorage.getItem('forgePRS')||'null')||defaultState;
const save=()=>localStorage.setItem('forgePRS',JSON.stringify(state));
const phases=[
 {name:'Phase 1',note:'Average intensity / average volume',sets:{speed:[6,2,.625],reps:[3,6,.80],power:[3,3,.85]}},
 {name:'Phase 2',note:'High intensity / lower volume',sets:{speed:[5,2,.70],reps:[5,4,.825],power:[3,2,.90]}},
 {name:'Phase 3',note:'Lower intensity / high volume',sets:{speed:[7,3,.625],reps:[3,6,.775],power:[4,3,.80]}},
 {name:'Peak',note:'Cut accessories, practise heavy work',sets:{speed:[3,2,.70],reps:[3,3,.80],power:[4,3,.90]}}
];
const blocks=[
 [{lift:'deadlift',type:'speed',title:'Deadlift Speed',acc:['Romanian Deadlift','Landmine Row','Pull-ups','Ab Wheel']},{lift:'bench',type:'reps',title:'Bench Reps',acc:['Incline DB Press','Weighted Dips','Rolling DB Extensions','Lateral Raises']},{lift:'squat',type:'power',title:'Squat Power',acc:['Pause Squat or Front Squat','Bulgarian Split Squat','RDL','Ab Wheel']},{lift:'viking',type:'speed',title:'Viking Press Speed',acc:['Touch & Go Bench','Chest Supported DB Row','Band Pull Aparts','Hammer Curls']}],
 [{lift:'deadlift',type:'reps',title:'Deadlift Reps',acc:['Block Pull or RDL','Landmine Row','Pull-ups','Farmers Carry']},{lift:'bench',type:'power',title:'Bench Power',acc:['Flat DB Press','Weighted Dips','Skull Crushers','Lateral Raises']},{lift:'squat',type:'speed',title:'Squat Speed',acc:['Front Squat','Bulgarian Split Squat','Good Morning','Hanging Knee Raises']},{lift:'viking',type:'reps',title:'Viking Press Reps',acc:['Bench Reps / T&G','Chest Supported DB Row','Rear Delt Raise','DB Curl']}],
 [{lift:'deadlift',type:'power',title:'Deadlift Power',acc:['Deficit Deadlift or RDL','Landmine Row','Pull-ups','Suitcase Carry']},{lift:'bench',type:'speed',title:'Bench Speed',acc:['Close Grip Bench','Incline DB Press','Dips','Band Pull Aparts']},{lift:'squat',type:'reps',title:'Squat Reps',acc:['Pause Squat','Walking Lunges','RDL','Ab Wheel']},{lift:'viking',type:'power',title:'Viking Press Power',acc:['Touch & Go Bench','Chest Supported DB Row','Lateral Raises','Hammer Curls']}]
];
function getSession(i=state.currentDay){let phase=Math.min(3,Math.floor(i/12));let block=Math.floor((i%12)/4);let day=i%4;return {...blocks[block][day],phase,block,day,week:Math.floor(i/4)+1,sessionNo:i+1};}
function workSets(s){let p=phases[s.phase].sets[s.type];let max=state.maxes[s.lift];let tm=s.phase<3?max*.95:max;let weight=round2p5(tm*p[2]);return {sets:p[0],reps:p[1],pct:p[2],weight,tm:round2p5(tm)}}
function warmups(weight){return [20,round2p5(weight*.4),round2p5(weight*.55),round2p5(weight*.7),round2p5(weight*.85)].filter((v,i,a)=>v<weight&&a.indexOf(v)===i).map((w,i)=>({w,r:i<2?5:i==2?3:i==3?2:1}))}
function render(){document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));let tab=document.getElementById('tab'+view[0].toUpperCase()+view.slice(1)); if(tab)tab.classList.add('active'); app.innerHTML=`<div class="wrap">${({home,log,progress,settings})[view]()}</div>`;}
function home(){let s=getSession();let w=workSets(s), total=state.maxes.deadlift+state.maxes.squat+state.maxes.bench;return `<div class="top"><div class="brand">Forge PRS</div><div class="pill">${phases[s.phase].name}</div></div><div class="card"><div class="muted">Week ${s.week} · Session ${s.sessionNo}/48</div><div class="session-title">${s.title}</div><div class="muted">${phases[s.phase].note}</div><div class="grid"><div class="stat"><span class="muted">Training max</span><b>${w.tm}</b><span>kg</span></div><div class="stat"><span class="muted">Today</span><b>${w.sets}×${w.reps}</b><span>@ ${w.weight}kg</span></div><div class="stat"><span class="muted">Total</span><b>${total}</b><span>kg / 500</span></div><div class="stat"><span class="muted">Lift</span><b>${state.maxes[s.lift]}</b><span>kg e1RM</span></div></div><button onclick="view='log';render()" style="width:100%;margin-top:16px">Start workout</button></div><div class="card"><b>Accessories</b>${s.acc.map(a=>`<div class="row"><span>${a}</span><span class="tag">log sets</span></div>`).join('')}</div><div class="card"><b>Cycle progress</b><p class="muted small">Complete sessions then advance. Miss a day? Just do the next session.</p><div class="phasegrid">${Array.from({length:48},(_,i)=>`<div class="box ${i<state.currentDay?'on':''}"></div>`).join('')}</div></div>`}
function log(){let s=getSession();let w=workSets(s);return `<div class="top"><div class="brand">Log</div><button class="secondary" onclick="completeWorkout()">Finish</button></div><div class="card"><div class="session-title">${s.title}</div><p class="muted">${w.sets} working sets of ${w.reps} reps @ ${w.weight}kg. Last set can be AMRAP, but don't miss reps.</p><b>Warm-up</b>${warmups(w.weight).map(x=>`<div class="row"><span>${x.w}kg × ${x.r}</span><button class="check" onclick="this.classList.toggle('done');this.textContent=this.classList.contains('done')?'✓':'○'">○</button></div>`).join('')}<b>Working sets</b><div id="mainsets">${Array.from({length:w.sets},(_,i)=>`<div class="set"><span>Set ${i+1}${i==w.sets-1?' +':''}</span><input value="${w.weight}" inputmode="decimal"><input value="${w.reps}" inputmode="numeric"><button class="check" onclick="this.classList.toggle('done');this.textContent=this.classList.contains('done')?'✓':'○'">○</button></div>`).join('')}</div><button class="ghost" style="width:100%;margin-top:10px" onclick="calcMain()">Calculate estimated max</button><div id="mainResult" class="muted" style="margin-top:10px"></div></div><div class="card"><b>Accessories</b>${s.acc.map(a=>accHtml(a)).join('')}</div>`}
function accHtml(name){let last=state.accessories[name]||{w:'',r1:'',r2:'',r3:''};return `<div class="card" style="background:#101014"><b>${name}</b><div class="set"><span>Weight</span><input id="${id(name)}w" value="${last.w}" inputmode="decimal"><input disabled value="kg"><span></span></div>${[1,2,3].map(i=>`<div class="set"><span>Set ${i}</span><input id="${id(name)}r${i}" value="${last['r'+i]}" inputmode="numeric"><input disabled value="reps"><span></span></div>`).join('')}<button class="secondary" onclick="saveAcc('${name.replaceAll("'","\\'")}')">Save</button></div>`}
function id(s){return s.replace(/[^a-z0-9]/gi,'')}
function saveAcc(name){state.accessories[name]={w:document.getElementById(id(name)+'w').value,r1:document.getElementById(id(name)+'r1').value,r2:document.getElementById(id(name)+'r2').value,r3:document.getElementById(id(name)+'r3').value};save();}
function calcMain(){let s=getSession();let inputs=[...document.querySelectorAll('#mainsets .set')];let last=inputs[inputs.length-1].querySelectorAll('input');let est=e1rm(parseFloat(last[0].value||0),parseInt(last[1].value||0));mainResult.innerHTML=`Estimated 1RM: <b>${est}kg</b> ${est>state.maxes[s.lift]?'<span class="ok">new estimated PR</span>':''}`; if(est>state.maxes[s.lift]){state.maxes[s.lift]=est;save();}}
function completeWorkout(){state.currentDay=Math.min(47,state.currentDay+1);save();view='home';render()}
function progress(){let total=state.maxes.deadlift+state.maxes.squat+state.maxes.bench;return `<div class="top"><div class="brand">Progress</div><div class="pill">${Math.round(total/500*100)}%</div></div><div class="card"><div class="big">${total}kg</div><div class="muted">Powerlifting total · goal 500kg</div><div class="bar" style="margin-top:14px"><span style="width:${Math.min(100,total/500*100)}%"></span></div></div><div class="grid">${Object.entries(state.maxes).map(([k,v])=>`<div class="stat"><span class="muted">${k[0].toUpperCase()+k.slice(1)}</span><b>${v}</b><span>kg</span></div>`).join('')}</div><div class="card"><b>Coach notes</b><p class="muted">If recovery is poor, skip AMRAP. If you beat target reps for 3 sessions on a lift, add 2.5kg to upper lifts or 5kg to lower lifts next cycle.</p></div>`}
function settings(){return `<div class="top"><div class="brand">Setup</div><button class="secondary" onclick="resetApp()">Reset</button></div><div class="card"><b>Current estimated 1RMs</b>${Object.keys(state.maxes).map(k=>`<label>${k[0].toUpperCase()+k.slice(1)} kg</label><input id="m_${k}" value="${state.maxes[k]}" inputmode="decimal">`).join('')}<button style="width:100%;margin-top:16px" onclick="saveMaxes()">Save maxes</button></div><div class="card"><b>Equipment profile</b><p class="muted">Rack, barbell, Ironmaster dumbbells, landmine, Viking Press, dip handles, pull-up bar, bands. No cable stack or leg machines.</p></div>`}
function saveMaxes(){Object.keys(state.maxes).forEach(k=>state.maxes[k]=parseFloat(document.getElementById('m_'+k).value||0));save();view='home';render()}
function resetApp(){if(confirm('Clear all Forge PRS data on this device?')){state=JSON.parse(JSON.stringify(defaultState));save();render()}}
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}render();
